### ISSUE TITLE
Unable to find channel

### ISSUE THREAD

**Issue by MrFums** [peakxl/twitch-drop-claimer#119]
Using the docker compose image - getting the below error
![image](https://github.com/peakxl/twitch-drop-claimer/assets/57535680/92f8119f-8338-4ddd-add9-cbf43c90f546)

Tried with 
```

EA Sports FC 24
Lost Ark
Tom Clancy's Rainbow Six Siege
```

All of them seem to get the same error even though there are campaigns for each for each of them. 

Compose:

```
version: '3.5'
services:
  twitch-drop-claimer:
    image: peakxy/twitch-watcher:latest
    restart: unless-stopped
    environment:
      - auth_token=redacted
      - category=EA Sports FC 24
      - watchAlwaysTopStreamer=true
      - claimDrops=true
      #- channelsWithPriority=illojuan,alexby11,aroyitt
      #- noChannelFoundWait=5
      #- userAgent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
      # - minWatching=15
      #- maxWatching=30
      #- streamerListRefresh=2
      #- streamerListRefreshUnit=hour
      #- browserScreenshot=false
      #- proxy=ip:port
      #- proxyAuth=username:password
    # volumes:
     # - "./screenshots:/usr/src/app/screenshots"
```
