### ISSUE TITLE
No channels available

### ISSUE THREAD

**Issue by brypl** [peakxl/twitch-drop-claimer#76]
Getting a no channels available error yet sign in works.

Have tried disabling drops setting, watch top streamer, setting preferred streamers and getting new auth token.

![image](https://user-images.githubusercontent.com/61400370/224702014-751839bd-0bd5-4eb6-bcc6-fc36961300ad.png)

This is my docker config

```

version: '3.5'
services:
  twitch-drop-claimer:
    image: peakxy/twitch-watcher:latest
    restart: unless-stopped
    environment:
      - auth_token=blankedoutforsecurity #Example value from readme
      - category=Sea%20of%20Thieves
      - watchAlwaysTopStreamer=true
      - claimDrops=true
      #- channelsWithPriority=illojuan,alexby11,aroyitt
      - noChannelFoundWait=1
      - userAgent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
      #- minWatching=10
      #- maxWatching=30
      #- streamerListRefresh=1
      #- streamerListRefreshUnit=hour
      #- browserScreenshot=true
      #- proxy=ip:port
      #- proxyAuth=username:password
    volumes:
      - "C:/DockerData/TwitchViewer:/screenshots"
```

**Comment by danshao** [comment]
<img width="545" alt="image" src="https://github.com/peakxl/twitch-drop-claimer/assets/449852/aea2e589-e4f2-4af6-b839-1c350dd924d9">
<img width="713" alt="image" src="https://github.com/peakxl/twitch-drop-claimer/assets/449852/655610cf-1083-4c3e-b0ff-ed7e3a247d70">

**Comment by danshao** [comment]
```
version: '3.5'
services:
  twitch-drop-claimer:
    image: peakxy/twitch-watcher:latest
    restart: unless-stopped    
    container_name: twitch-watcher
    environment:
      - auth_token=mytwitchauthtoken
      - category=Baldur's%20Gate%203
      - watchAlwaysTopStreamer=false
      - claimDrops=true 
      - channelsWithPriority=quin69,singsing,cohhcarnage
      - noChannelFoundWait=1
      #- userAgent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
      #- minWatching=15
      #- maxWatching=30
      #- streamerListRefresh=2
      #- streamerListRefreshUnit=hour
      #- browserScreenshot=false
      #- proxy=ip:port
      #- proxyAuth=username:password
    #volumes:
    #  - "./screenshots:/usr/src/app/screenshots"
```
